[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# trigger eh context
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if not copier then set_consumeable_usage(self) end"
position = "before"
payload = '''
if self.ability.set == 'Planet' then
	SMODS.calculate_context({ ccc_event_horizon = true, planet = self })
end
if self.event_horizoned then
	delay(0.75)
	G.E_MANAGER:add_event(Event({trigger = 'before',delay = 0.75,func = function() self:flip();play_sound('card1', 1);self:juice_up(0.3, 0.3);return true end }))
	G.E_MANAGER:add_event(Event({trigger = 'before',delay = 0.75,func = function() self:set_sprites(G.P_CENTERS.c_black_hole);return true end }))
	G.E_MANAGER:add_event(Event({trigger = 'before',delay = 0.75,func = function() self:flip();play_sound('tarot2', 1, 0.6);self:juice_up(0.3, 0.3);return true end }))
	self:set_ability(G.P_CENTERS.c_black_hole, nil, true)
end
'''
match_indent = true