[manifest]
version = "1.0.1"
dump_lua = true
priority = 0

# ccc_cash_out calculate
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.deck:hard_set_T()"
position = "before"
payload = '''
for i = 1, #G.jokers.cards do
	G.jokers.cards[i]:calculate_joker({ccc_cash_out = true})
end
'''
match_indent = true

# ccc_paid_booster calculate
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.cost > 0 then"
position = "after"
payload = '''
for i = 1, #G.jokers.cards do
	G.jokers.cards[i]:calculate_joker({ccc_paid_booster = true, card = self})
end
'''
match_indent = true