[manifest]
version = '1.0.0'
dump_lua = true
priority = 0

# Add info_queue bubbles if needed
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'before'
pattern = '''
local cols
'''
payload = '''
if obj and obj.artist_credits and Ortalab.config.credit_pos == 2 then
    for _, artist in ipairs(obj.artist_credits) do
        info_boxes[#info_boxes+1] =
            {n=G.UIT.R, config={align = "cm"}, nodes={
                {n=G.UIT.R, config={align = "cm", colour = lighten(G.C.JOKER_GREY, 0.5), r = 0.1, padding = 0.05, emboss = 0.05}, nodes={
                    {n=G.UIT.R, config={align = "cm", colour = darken(loc_colour(artist), 0.15), r = 0.1}, nodes={
                        {n=G.UIT.R, config={align = "tm", minh = 0.36, padding = 0.03}, nodes={
                            {n=G.UIT.T, config={text = localize('ortalab_artist'), scale = 0.32, colour = G.C.UI.TEXT_LIGHT}}
                        }},
                        {n=G.UIT.R, config={align = "cm", minw = 1.5, minh = 0.4, r = 0.1, padding = 0.05, colour = lighten(loc_colour(artist), 0.5)}, nodes={
                            {n=G.UIT.R, config={align = "cm", padding = 0.03}, nodes={
                                {n=G.UIT.R, config = {align = 'tm'}, nodes = {
                                    {n=G.UIT.O, config={
                                        object = DynaText({string = localize{type = 'raw_descriptions', set = 'Ortalab Artist', key = artist},
                                        colours = {G.C.UI.TEXT_DARK},
                                        silent = true,
                                        pop_in = 0,
                                        pop_in_rate = 4,
                                        y_offset = -0.6,
                                        scale =  0.27
                                        })
                                    }}
                                }}
                            }}
                        }}
                    }}
                }}
            }}
    end
end

'''

# Blind credits in hud
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
match_indent = true
position = 'after'
pattern = '''
{n=G.UIT.R, config={align = "cm",padding = 0.15}, nodes={
          {n=G.UIT.O, config={object = G.GAME.blind, draw_layer = 1}},
          {n=G.UIT.C, config={align = "cm",r = 0.1, padding = 0.05, emboss = 0.05, minw = 2.9, colour = G.C.BLACK}, nodes={
            {n=G.UIT.R, config={align = "cm", maxw = 2.8}, nodes={
              {n=G.UIT.T, config={text = localize('ph_blind_score_at_least'), scale = 0.3, colour = G.C.WHITE, shadow = true}}
            }},
            {n=G.UIT.R, config={align = "cm", minh = 0.6}, nodes={
              {n=G.UIT.O, config={w=0.5,h=0.5, colour = G.C.BLUE, object = stake_sprite, hover = true, can_collide = false}},
              {n=G.UIT.B, config={h=0.1,w=0.1}},
              {n=G.UIT.T, config={ref_table = G.GAME.blind, ref_value = 'chip_text', scale = 0.001, colour = G.C.RED, shadow = true, id = 'HUD_blind_count', func = 'blind_chip_UI_scale'}}
            }},
            {n=G.UIT.R, config={align = "cm", minh = 0.45, maxw = 2.8, func = 'HUD_blind_reward'}, nodes={
              {n=G.UIT.T, config={text = localize('ph_blind_reward'), scale = 0.3, colour = G.C.WHITE}},
              {n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'dollars_to_be_earned'}}, colours = {G.C.MONEY},shadow = true, rotate = true, bump = true, silent = true, scale = 0.45}),id = 'dollars_to_be_earned'}},
            }},
          }},
        }},
'''
payload = '''
{n=G.UIT.R, config = {align = 'tm', id = 'HUD_blind_badge', func = 'HUD_blind_badge', minh = 0.4}, nodes = 
	Ortalab.config.reduced_mod_badge and {
		{n=G.UIT.T, config={text = localize('blind_credit'), scale = 0.3, colour = G.C.WHITE, shadow = true}},
		{n=G.UIT.T, config={text = '', scale = 0.3, colour = G.C.WHITE, shadow = true}},
	} or {
		{n=G.UIT.R, config={align = "cm", minh = 0.6}, nodes={
			{n=G.UIT.R, config={align = "cm", colour = G.C.GREEN, r = 0.1, minw = 2, minh = 0.36, emboss = 0.05, padding = 0.03*0.9}, nodes={
				{n=G.UIT.B, config={h=0.1,w=0.03}},
				{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.blind_badge, ref_value = 'name'}}, colours = {G.C.WHITE},float = true, shadow = true, offset_y = -0.05, silent = true, spacing = 1, scale = 0.33*0.9})}},
				{n=G.UIT.B, config={h=0.1,w=0.03}},
			}}
		}}
	}
},
'''
