[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

## Shop Card Area Width
[[patches]]
[patches.pattern]
target = 'tag.lua'
pattern = '''self.pos = proto.pos'''
position = 'after'
match_indent = true
payload = '''self.soul_pos = proto.soul_pos'''

[[patches]]
[patches.pattern]
target = 'tag.lua'
pattern = '''tag_sprite.T.scale = 1'''
position = 'before'
match_indent = true
payload = '''if G.P_TAGS[self.key].soul_pos and G.P_TAGS[self.key].discovered then
    tag_sprite.soul = Sprite(0,0,_size*1,_size*1, G.ASSET_ATLAS[G.P_TAGS[self.key].atlas], G.P_TAGS[self.key].soul_pos)

end'''

[[patches]]
[patches.pattern]
target = 'engine/sprite.lua'
pattern = '''for k, v in pairs(self.children) do'''
position = 'before'
match_indent = true
payload = '''
if self.soul then
    local scale_mod = 0.07 + 0.02*math.sin(1.8*G.TIMERS.REAL) + 0.00*math.sin((G.TIMERS.REAL - math.floor(G.TIMERS.REAL))*math.pi*14)*(1 - (G.TIMERS.REAL - math.floor(G.TIMERS.REAL)))^3
    local rotate_mod = 0.05*math.sin(1.219*G.TIMERS.REAL) + 0.00*math.sin((G.TIMERS.REAL)*math.pi*5)*(1 - (G.TIMERS.REAL - math.floor(G.TIMERS.REAL)))^2
    self.soul:draw_shader('dissolve',0, nil, nil, self, scale_mod, rotate_mod,nil, 0.05 + 0.03*math.sin(1.8*G.TIMERS.REAL),nil, 0.6)
    self.soul:draw_shader('dissolve', nil, nil, nil, self, scale_mod, rotate_mod,nil, -0.05)
end
'''

# Slayer Patch
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.FUNCS.draw_from_discard_to_deck()'''
position = 'after'
match_indent = true
payload = '''
G.GAME.blinds_defeated = (G.GAME.blinds_defeated or 0) + 1
'''

# Dandy Patch
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''G.GAME.unused_discards = (G.GAME.unused_discards or 0) + G.GAME.current_round.discards_left'''
position = 'before'
match_indent = true
payload = '''
G.GAME.unused_hands = (G.GAME.unused_hands or 0) + G.GAME.current_round.hands_left
'''

## Constellation Patch
#[[patches]]
#[patches.pattern]
#target = 'functions/UI_definitions.lua'
#pattern = '''G.GAME.orbital_choices = G.GAME.orbital_choices or {}'''
#position = 'before'
#match_indent = true
#payload = '''
#G.GAME.zodiac_choices = G.GAME.zodiac_choices or {}
#G.GAME.zodiac_choices[G.GAME.round_resets.ante] = G.GAME.zodiac_choices[G.GAME.round_resets.ante] or {}
#
#if not G.GAME.zodiac_choices[G.GAME.round_resets.ante][type] then 
#    local _poker_hands = {}
#    for k, _ in pairs(G.ZODIACS) do
#        if k ~= 'zodiac_ortalab_ophiuchus' then
#            _poker_hands[#_poker_hands+1] = k
#        end
#    end
#
#    local zodiac = pseudorandom_element(_poker_hands, pseudoseed('constellation_patch'))
#    G.GAME.zodiac_choices[G.GAME.round_resets.ante][type] = zodiac
#end
#'''

[[patches]]
[patches.pattern]
target = 'tag.lua'
pattern = '''orbital_hand = '['..localize('k_poker_hand')..']','''
position = 'before'
match_indent = true
payload = '''
zodiac_hands = {'['..localize('k_poker_hand')..']', '['..localize('k_poker_hand')..']'},
'''
[[patches]]
[patches.pattern]
target = 'tag.lua'
pattern = '''add_tag(Tag(_context.tag.key))'''
position = 'at'
match_indent = true
payload = '''
add_tag(Tag(_context.tag.key, false, _context.tag.ability.blind_type))
'''

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''local _tag = Tag(G.GAME.round_resets.blind_tags[blind_choice], nil, blind_choice)'''
position = 'after'
match_indent = true
payload = '''
_tag:set_ability()
'''

# Common Patch - Spawn Extra Cards
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
position = 'after'
pattern = '''
for i = 1, G.GAME.shop.joker_max - #G.shop_jokers.cards do
    G.shop_jokers:emplace(create_card_for_shop(G.shop_jokers))
end
'''
payload = '''
for k, v in ipairs(G.GAME.tags) do
    v:apply_to_run({type = 'ortalab_shop_add', area = G.shop_jokers})
end
'''

# Hand play tag context
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
position = 'after'
pattern = '''
local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)
'''
payload = '''
for k, v in ipairs(G.GAME.tags) do
    v:apply_to_run({type = 'ortalab_hand_played'})
end
'''

# First hand drawn
[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
position = 'after'
pattern = '''
-- removed first hand drawn context
'''
payload = '''
G.E_MANAGER:add_event(Event({
    trigger = 'immediate',
    func = function()
        for k, v in ipairs(G.GAME.tags) do
            v:apply_to_run({type = 'ortalab_first_hand'})
        end
        return true
    end
}))
'''


# TEMP PATCH - Stock voucher redeeming
[[patches]]
[patches.pattern]
target = 'cardarea.lua'
match_indent = true
position = 'at'
pattern = '''
(self.config.type == 'hand' and state == G.STATES.SMODS_BOOSTER_OPENED) or
'''
payload = '''
(self.config.type == 'hand' and (state == G.STATES.SMODS_BOOSTER_OPENED or state == G.STATES.SMODS_REDEEM_VOUCHER)) or
'''