[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "for _, area in ipairs(SMODS.get_card_areas('jokers')) do for _, _card in ipairs(area.cards) do"
position = "before"
match_indent = true
payload = '''
SMODS.calculate_context {
  paperback = {
    before_joker_effects = true
  }
}
'''
