[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'if not SMODS.config.seeded_unlocks and (G.GAME.seeded or G.GAME.challenge) then return end'
position = "before"
match_indent = true
payload = "if not (card or {}).paperback_challenge_unlock then"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'card = card or {}'
position = "before"
match_indent = true
payload = "end"

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'if card.unlocked or card.wip then return end'
position = "before"
match_indent = true
payload = "end"
