[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "G.FUNCS.play_cards_from_highlighted = function(e)"
position = "after"
match_indent = true
payload = '''
  G.GAME.paperback.da_capo_suit = PB_UTIL.da_capo_cycle(G.GAME.paperback.da_capo_suit)
'''

  