[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "G.GAME.last_tarot_planet = card.config.center_key"
position = "after"
match_indent = true
payload = '''
G.GAME.paperback.last_tarot_energized = card.ability and card.ability.paperback_energized
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local card = create_card('Tarot_Planet', G.consumeables, nil, nil, nil, nil, G.GAME.last_tarot_planet, 'fool')"
position = "after"
match_indent = true
payload = '''
if G.GAME.paperback.last_tarot_energized then
  G.GAME.paperback.last_tarot_energized = false
  card.ability.paperback_energized = true
end
'''
