SMODS.Atlas {
  key = 'Jokers',
  path = 'Jokers.png',
  px = 71,
  py = 95 
}

SMODS.Atlas {
  key = 'Plump_joker',
  path = 'Plump_joker.png',
  px = 80,
  py = 95 
}

local JokerAtlasKeys = {
  'absent_heart',
  'accountant',
  'atom',
  'avocado',
  'balance',
  'bankaccount',
  'bazaar',
  'beanstalk',
  'blood_moon',
  'bonsai',
  'breakfast_cereal',
  'burdenofgreatness',
  'catalogue',
  'checklist',
  'cleanslate',
  'cloverfield',
  'conga_line',
  'count_orlok',
  'dancing_moves',
  'dealer',
  'delirium_alt0',
  'delirium_alt1',
  'delirium_alt2',
  'delirium_alt3',
  'desolate',
  'equity',
  'fabergeegg',
  'fabergeegg_soul',
  'fan_mail',
  'feather_marvelous',
  'feather_precious',
  'feather_silky',
  'feather_vibrant',
  'flipflop_even',
  'flipflop_odd',
  'golden_idol',
  'goldfish',
  'grapes',
  'grey_joker',
  'hannysvoorwerp',
  'hecate',
  'hecate_soul',
  'heirloom',
  'joker_reject',
  'kudzu',
  'lady_in_waiting',
  'lady_of_the_lake',
  'lady_of_the_lake_soul',
  'legions',
  'lightning',
  'long_road',
  'lotteryticket',
  'membership_card',
  'metropolis',
  'minimalist',
  'mirror_lake',
  'overflow',
  'parrot',
  'prairie',
  'prehistory',
  'primality',
  'purple_card',
  'recycle',
  'roller_skates',
  'self_assembly',
  'serial',
  'sextant',
  'skinner_box',
  'slashed_joker',  
  'slashed_joker_soul',
  'snow_shovel',
  'spooky_joker',
  'sputnik',
  'star_chart',
  'star_chart_soul',
  'theater',
  'throne_active',
  'throne_inactive',
  'train_ticket',
  'truffle',
  'wanted',
  'waveform',
  'waveform_soul',
  'windowsill',
  'wishbone',
  'indicator_hands',
  'indicator_planets',
  'indicator_ranks',
  'microwave',
}

local JokerAtlasTable = {}
for i, key in ipairs(JokerAtlasKeys) do
  JokerAtlasTable[key] = i - 1
end
JokerAtlasKeys = nil

function RainyDays.GetJokersAtlasTable(key)
  local pos = JokerAtlasTable[key]
  return { x = pos % 10, y = math.floor(pos / 10) }
end