---- SMODS.Joker {
----   key = 'atom',
----   name = 'Atom',
----   atlas = 'Jokers',
----   rarity = 2,
----   cost = 7,
----   unlocked = true, 
----   discovered = true,
----   blueprint_compat = true,
----   eternal_compat = true,
----   perishable_compat = true,
----   pos = GetJokersAtlasTable('atom'),
----   config = {
----     extra = {
----       rank = 'Ace',
----       numerator_in = 1,
----       denominator_in = 4,
----       chips_rewards = 20
----     }
----   },
  
----   loc_vars = function(self, info_queue, card)
----     local numerator_out, denominator_out = SMODS.get_probability_vars(card, card.ability.extra.numerator_in, card.ability.extra.denominator_in)
----     return {
----       vars = {
----         localize(card.ability.extra.rank, 'ranks'),
----         numerator_out, 
----         denominator_out,
----         card.ability.extra.chips_rewards
----       }
----     }
----   end,
  
----   calculate = function(self, card, context)
----     if context.individual and context.cardarea == G.play and context.other_card.base.value == card.ability.extra.rank then
----       if SMODS.pseudorandom_probability(card, 'atom', card.ability.extra.numerator_in, card.ability.extra.denominator_in) then
----         level_up_table_tailends(card, { context.scoring_name}, nil, false, 0, card.ability.extra.chips_rewards)
----       end
----     end
----   end
---- }