[manifest]
version = "1.0.0" 
dump_lua = true
priority = 9999999

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''G.SPLASH_BACK:define_draw_steps({{
    shader = 'splash',
    send = {
        {name = 'time', ref_table = G.SANDBOX, ref_value = 'vort_time'},
        {name = 'vort_speed', val = 0.4},
        {name = 'colour_1', ref_table = G.SANDBOX, ref_value = 'col1'},
        {name = 'colour_2', ref_table = G.SANDBOX, ref_value = 'col2'},
        {name = 'mid_flash', ref_table = G.SANDBOX, ref_value = 'mid_flash'},
        {name = 'vort_offset', val = 0},
}}})'''
position = "at"
payload = '''
G.SPLASH_BACK:define_draw_steps({{
    shader = 'splash',
    send = {
        {name = 'time', ref_table = G.SANDBOX, ref_value = 'vort_time'},
        {name = 'vort_speed', val = 0.4},
        {name = 'colour_1', ref_table = G.C, ref_value = 'LOSTED_OUTER'},
        {name = 'colour_2', ref_table = G.C, ref_value = 'LOSTED_INNER'},
        {name = 'mid_flash', ref_table = G.SANDBOX, ref_value = 'mid_flash'},
        {name = 'vort_offset', val = 0},
}}})
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
    tab_definition_function_args = 'Audio'
  }
'''
position = "after"
payload = '''
  tabs[#tabs+1] = {
      label = localize('k_losted_themes_tab'),
      tab_definition_function = G.UIDEF.settings_tab,
      tab_definition_function_args = 'Themes'
  }
'''
match_indent = true