[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

### Lost Edition - Wild Card Debuff Immunity 
[[patches]]
[patches.pattern]
target = 'blind.lua'
pattern = "if self.debuff.suit and card:is_suit(self.debuff.suit, true) then"
position = 'at' 
payload = "if self.debuff.suit and card:is_suit(self.debuff.suit, true) and card.ability.name ~= 'Wild Card' then"
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'self.debuff = should_debuff'
position = 'after'
match_indent = true
payload = '''
if not self.debuff then self.debuffed_by_blind = false end
'''