---- SMODS.Joker {
----   key = "wheat_field",
----   config = {
----     extra = {
----       xMult = 1.075,
----       xMult_gain = 0.075,
----       xMult_base = 1.075,
----       suit = "paperback_Crowns",
----     }
----   },
----   rarity = 2,
----   pos = { x = 3, y = 10 },
----   atlas = "jokers_atlas",
----   cost = 6,
----   unlocked = true,
----   discovered = false,
----   blueprint_compat = true,
----   eternal_compat = true,
----   paperback = {
----     requires_crowns = true,
----   },

----   loc_vars = PB_UTIL.panorama_loc_vars,
----   calculate = PB_UTIL.panorama_logic,
----   joker_display_def = PB_UTIL.panorama_joker_display_def
---- }
