
[manifest]
version = "1.0.0"
dump_lua = true
priority = 0


#Negative bonus chips UI
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
bonus_chips = (self.ability.bonus + (self.ability.perma_bonus or 0)) > 0 and (self.ability.bonus + (self.ability.perma_bonus or 0)) or nil,
'''
position = 'at'
match_indent = true
payload = '''
bonus_chips = (self.ability.bonus + (self.ability.perma_bonus or 0)) ~= 0 and (self.ability.bonus + (self.ability.perma_bonus or 0)) or nil,
'''


#Burglar instant for Bobby compat
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
ease_discard(-G.GAME.current_round.discards_left, nil, true)
'''
position = 'at'
payload = '''
ease_discard(-G.GAME.current_round.discards_left, true, true)
'''
match_indent = true


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''
ease_hands_played(self.ability.extra)
'''
position = 'at'
payload = '''
ease_hands_played(self.ability.extra, true)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
idol_card = {suit = 'Spades', rank = 'Ace'},
mail_card = {rank = 'Ace'},
ancient_card = {suit = 'Spades'},
'''
position = 'after'
payload = '''
tuxedo_card = {suit = 'Spades'},
farmer_card = {suit = 'Spades'},
fish_rank = {rank = 'Ace'},
'''
match_indent = true
