return {
  blinds_enabled = true,
  minor_arcana_enabled = false,
  suits_enabled = false,
  enhancements_enabled = false,
  editions_enabled = true,
  paperclips_enabled = true,
  vouchers_enabled = false,
  tags_enabled = true,
  ranks_enabled = false,
  ego_gifts_enabled = false,
  spectrals_enabled = false,
  plague_doctor_quotes_enabled = false,
  show_credits = true,
  upgrade_indicators = true,
}
