[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if splashed and not unsplashed then table.insert(final_scoring_hand, G.play.cards[i]) end"
position = "after"
match_indent = true
payload = '''
  if final_scoring_hand[#final_scoring_hand] then
    if not SMODS.has_no_suit(final_scoring_hand[#final_scoring_hand]) then
      G.GAME.paperback.last_scored_suit = final_scoring_hand[#final_scoring_hand].base.suit
    end
  end
'''
