[manifest]
version = "1.0.0"
dump_lua = true
priority = 9999999

# create the neagtive rate
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "edition_rate = 1,"
position = "after"
payload = "negative_rate = 1,"
match_indent = true

# Add quantum and plasma editions
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''_options = { 'e_negative', 'e_polychrome', 'e_holo', 'e_foil' }'''
position = 'after'
match_indent = true
payload = '''		if _key == "wheel_of_fortune" or _key == "aura" then
			_options[#_options+1] = "e_losted_quantum"
		end
		if _key == "wheel_of_fortune" then
			_options[#_options+1] = "e_losted_plasma"
		end'''