[manifest]
version = "1.0.0"
dump_lua = true
priority = 2

    # Prevent "USE" button on Joker Collectables in deck
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
end
if card.ability.consumeable then
'''
position = "after"
payload = '''
    if card.config.center.key == 'c_artb_joker_collectable' or card.config.center.key == 'c_artb_limited_edition_collectable' or card.config.center.key == 'c_artb_gros_michel_collectable' or card.config.center.key == 'c_artb_cavendish_collectable' then
        return {
        n=G.UIT.ROOT, config = {padding = 0, colour = G.C.CLEAR}, nodes={
            {n=G.UIT.C, config={padding = 0.15, align = 'cl'}, nodes={
            {n=G.UIT.R, config={align = 'cl'}, nodes={
                sell
            }},
            }},
        }}
    end
'''
match_indent = true