[manifest]
version = "1.0.0"
priority = 0

# Trigger tags on game over
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
SMODS.calculate_context({end_of_round = true, game_over = game_over, beat_boss = G.GAME.blind.boss, scoring_hand = SMODS.last_hand.scoring_hand, scoring_name = SMODS.last_hand.scoring_name, full_hand = SMODS.last_hand.full_hand })
'''
position = "after"
payload = '''
for i = 1, #G.GAME.tags do
    if not SMODS.saved then
        G.GAME.tags[i]:apply_to_run({type = 'game_over'})
    end
end
'''
match_indent = true
