[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = '''
G.ARGS.TEMP_POOL = EMPTY(G.ARGS.TEMP_POOL)
'''
position = "after"
payload = '''
if next(SMODS.find_card('j_cod_elitism')) then
    SMODS.remove_pool(available_rarities, "Common")
end
'''
match_indent = true
